# autostart.conf
exec-once = systemctl --user start hyprpolkitagent
exec-once = uwsm app -- hyprpaper
exec-once = uwsm app -- waybar
exec-once = uwsm app -- AppImageLauncher
exec-once = /home/rshirts/bash/autoupdate.sh
