# environment.conf
# cursor stuff
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
# gtk/qt stuff
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt5ct
env = GTK_THEME,Arc-Dark
env = GTK_THEME_VARIANT,dark
# ssh stuff
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/ssh-agent.socket
