# hyprland.conf

source = /home/rshirts/.config/hypr/monitors.conf
source = /home/rshirts/.config/hypr/keybinds.conf
source = /home/rshirts/.config/hypr/autostart.conf
source = /home/rshirts/.config/hypr/environment.conf
source = /home/rshirts/.config/hypr/layout.conf
source = /home/rshirts/.config/hypr/devices.conf
source = /home/rshirts/.config/hypr/windowrules.conf
